- name: Download Node Exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner : bin
    group : bin

- name: Copy Node Exporter Service File
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start Node_Exporter Service
  ansible.builtin.systemd_service:
    name : Node_Exporter
    state : restarted
    enabled: yes
    daemon-reload : yes



